2016/05/10 23:09:39 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing directory or file.' in C:\xampp\htdocs\web\framework\YiiBase.php:348
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('bootstrap')
#3 C:\xampp\htdocs\web\protected\views\layouts\main.php(19): CModule->__get('bootstrap')
#4 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#11 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#12 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): CController->render('index')
#16 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#17 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#21 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#22 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/web/index.php
---
2016/05/10 23:15:06 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing directory or file.' in C:\xampp\htdocs\web\framework\YiiBase.php:348
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('bootstrap')
#3 C:\xampp\htdocs\web\protected\views\layouts\main.php(19): CModule->__get('bootstrap')
#4 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#11 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#12 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): CController->render('index')
#16 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#17 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#21 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#22 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/web/index.php
---
2016/05/10 23:16:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'web'@'localhost' (using password: YES)' in C:\xampp\htdocs\web\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\web\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\web\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\web\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\web\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/web/index.php?r=gii
---
2016/05/10 23:16:43 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing directory or file.' in C:\xampp\htdocs\web\framework\YiiBase.php:348
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('bootstrap')
#3 C:\xampp\htdocs\web\protected\views\layouts\main.php(19): CModule->__get('bootstrap')
#4 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#11 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#12 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\web\framework\web\actions\CViewAction.php(140): CController->render('pages/about')
#16 C:\xampp\htdocs\web\framework\web\actions\CAction.php(76): CViewAction->run()
#17 C:\xampp\htdocs\web\framework\web\CController.php(308): CAction->runWithParams(Array)
#18 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#19 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#20 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('page')
#21 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#22 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/web/index.php?r=site/page&view=about
HTTP_REFERER=http://localhost/web/index.php?r=site/contact
---
2016/05/10 23:31:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'web'@'localhost' (using password: YES)' in C:\xampp\htdocs\web\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\web\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\web\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\web\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\web\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/web/index.php?r=gii
---
2016/05/10 23:31:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'web'@'localhost' (using password: YES)' in C:\xampp\htdocs\web\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\web\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\web\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\web\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\web\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost/web/index.php?r=gii
---
2016/05/10 23:31:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'web'@'localhost' (using password: YES)' in C:\xampp\htdocs\web\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\web\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\web\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\web\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\web\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/web/index.php?r=gii
---
2016/05/10 23:32:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'web'@'localhost' (using password: YES)' in C:\xampp\htdocs\web\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\web\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\web\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\web\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\web\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/web/index.php?r=gii
---
2016/05/10 23:39:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'web'@'localhost' (using password: YES)' in C:\xampp\htdocs\web\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\web\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\web\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\web\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\web\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/web/index.php?r=gii
---
2016/05/10 23:39:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gi".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gi')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/index.php?r=gi
---
2016/05/10 23:39:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'web'@'localhost' (using password: YES)' in C:\xampp\htdocs\web\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\web\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\web\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\web\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\web\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\web\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\web\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\web\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/web/index.php?r=gii
---
2016/05/11 00:02:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "ersror".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('ersror')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('ersror')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/ersror')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php?r=site/ersror
---
2016/05/11 00:02:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "efrror".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('efrror')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('efrror')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/efrror')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php?r=site/efrror
---
2016/05/11 00:02:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "sefse".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('sefse')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('sefse')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/sefse')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php?r=site/sefse
---
2016/05/11 00:05:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "_view".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('_view')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('_view')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente/_view')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php?r=cliente/_view
---
2016/05/11 00:05:21 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\web\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente/update')
#10 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/web/index.php?r=cliente/update
---
2016/05/11 00:05:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "_view.php".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('_view.php')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('_view.php')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente/_view.p...')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php?r=cliente/_view.php
---
2016/05/11 00:05:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente/index.p...')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php?r=cliente/index.php
---
2016/05/11 21:18:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente/admin')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/index.php?r=cliente/admin
HTTP_REFERER=http://localhost/web/index.php?r=cliente/index
---
2016/05/11 22:15:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "about".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('about')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('about')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/about')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php/site/about
HTTP_REFERER=http://localhost/web/index.php/site/contact
---
2016/05/11 22:21:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "handicap/index".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap/index')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/index.php/handicap/index
HTTP_REFERER=http://localhost/web/index.php/estado/index
---
2016/05/11 23:33:53 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\web\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cita/update')
#10 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/web/index.php/cita/update
HTTP_REFERER=http://localhost/web/index.php/site/login
---
2016/05/12 21:59:05 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\layouts\front.php:6)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(784): CalendarioController->renderFile()
#1 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CalendarioController->render()
#2 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#3 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#5 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#6 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/calendario/index
in C:\xampp\htdocs\web\protected\views\layouts\front.php (6)
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/12 22:00:33 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\layouts\front.php:6)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(784): CalendarioController->renderFile()
#1 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CalendarioController->render()
#2 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#3 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#5 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#6 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/calendario/index
in C:\xampp\htdocs\web\protected\views\layouts\front.php (6)
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/12 22:01:00 [error] [exception.CException] exception 'CException' with message 'CalendarioController cannot find the requested view "_tab_generales".' in C:\xampp\htdocs\web\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\widgets\CTabView.php(217): CController->renderPartial('_tab_generales', '$model')
#1 C:\xampp\htdocs\web\framework\web\widgets\CTabView.php(149): CTabView->renderBody()
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(181): CTabView->run()
#3 C:\xampp\htdocs\web\protected\views\layouts\front.php(22): CBaseController->widget('CTabView', Array)
#4 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CController->render('index')
#8 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#9 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('calendario/inde...')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php/calendario/index
---
2016/05/14 14:18:34 [error] [php] Object of class CInlineAction could not be converted to string (C:\xampp\htdocs\web\protected\views\calendario\index.php:13)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): CalendarioController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): CalendarioController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CalendarioController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/calendario/index
in C:\xampp\htdocs\web\protected\views\calendario\index.php (13)
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/14 14:18:53 [error] [php] Object of class CInlineAction could not be converted to string (C:\xampp\htdocs\web\protected\views\calendario\index.php:13)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): CalendarioController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): CalendarioController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CalendarioController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/calendario/index
in C:\xampp\htdocs\web\protected\views\calendario\index.php (13)
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/14 14:19:10 [error] [php] Object of class CInlineAction could not be converted to string (C:\xampp\htdocs\web\protected\views\calendario\index.php:13)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): CalendarioController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): CalendarioController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CalendarioController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/calendario/index
in C:\xampp\htdocs\web\protected\views\calendario\index.php (13)
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/14 14:19:21 [error] [php] Object of class CInlineAction could not be converted to string (C:\xampp\htdocs\web\protected\views\calendario\index.php:13)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): CalendarioController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): CalendarioController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CalendarioController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/calendario/index
in C:\xampp\htdocs\web\protected\views\calendario\index.php (13)
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/14 14:19:41 [error] [php] Object of class CInlineAction could not be converted to string (C:\xampp\htdocs\web\protected\views\calendario\index.php:13)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): CalendarioController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): CalendarioController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CalendarioController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/calendario/index
in C:\xampp\htdocs\web\protected\views\calendario\index.php (13)
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/14 16:49:26 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\registro\index.php:35)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): RegistroController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): RegistroController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\RegistroController.php(10): RegistroController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): RegistroController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): RegistroController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): RegistroController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): RegistroController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/registro/index
in C:\xampp\htdocs\web\protected\views\registro\index.php (35)
in C:\xampp\htdocs\web\protected\controllers\RegistroController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/14 16:51:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\web\protected\controllers\ClienteController.php:157
Stack trace:
#0 C:\xampp\htdocs\web\protected\controllers\ClienteController.php(89): ClienteController->loadModel('2')
#1 [internal function]: ClienteController->actionUpdate('2')
#2 C:\xampp\htdocs\web\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(ClienteController), Array)
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ClienteController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('update')
#13 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente/update')
#14 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/web/index.php/cliente/update/2
---
2016/05/14 17:04:28 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\registro\index.php:35)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): RegistroController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): RegistroController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\RegistroController.php(10): RegistroController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): RegistroController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): RegistroController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): RegistroController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): RegistroController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/registro
in C:\xampp\htdocs\web\protected\views\registro\index.php (35)
in C:\xampp\htdocs\web\protected\controllers\RegistroController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/14 17:05:20 [error] [php] Undefined variable: form (C:\xampp\htdocs\web\protected\views\registro\index.php:25)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): RegistroController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): RegistroController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\RegistroController.php(10): RegistroController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): RegistroController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): RegistroController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): RegistroController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): RegistroController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/index.php/registro
in C:\xampp\htdocs\web\protected\views\registro\index.php (25)
in C:\xampp\htdocs\web\protected\controllers\RegistroController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/14 18:43:01 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/mano/index
HTTP_REFERER=http://localhost/web/index.php/estado/index
---
2016/05/14 18:43:14 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/mano/index
HTTP_REFERER=http://localhost/web/index.php/estado/index
---
2016/05/14 18:46:26 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/estado/index
HTTP_REFERER=http://localhost/web/index.php/cliente/index
---
2016/05/14 18:46:28 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/cliente/index
HTTP_REFERER=http://localhost/web/index.php/otro/index
---
2016/05/14 18:46:28 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/otro/index
HTTP_REFERER=http://localhost/web/index.php/cita/index
---
2016/05/14 18:46:29 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/cita/index
HTTP_REFERER=http://localhost/web/index.php/estado/index
---
2016/05/14 18:46:29 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/mano/index
HTTP_REFERER=http://localhost/web/index.php/estado/index
---
2016/05/14 18:46:31 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/admin
---
2016/05/14 18:46:31 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php/admin
---
2016/05/14 18:46:38 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/index.php
---
2016/05/14 19:06:22 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/handicap/index
HTTP_REFERER=http://localhost/web/site/index
---
2016/05/14 19:06:34 [error] [exception.CException] exception 'CException' with message 'Property "CUrlManager.ulrSuffix" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\YiiBase.php(220): CComponent->__set('ulrSuffix', '.html')
#1 C:\xampp\htdocs\web\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\web\framework\base\CApplication.php(531): CModule->getComponent('urlManager')
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#6 {main}
REQUEST_URI=/web/handicap/index.html
---
2016/05/14 19:06:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.html".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('index.html')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index.html')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap/index....')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/handicap/index.html
---
2016/05/14 19:06:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.html".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('index.html')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index.html')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap/index....')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/handicap/index.html
---
2016/05/14 19:32:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/admin".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/admin')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/admin
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 19:32:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/admin".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/admin')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/admin
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 19:32:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/admin".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/admin')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/admin
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 19:33:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/admin".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/admin')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/admin
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 19:34:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "localhost/admin".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('localhost/admin')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/localhost/admin
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 19:55:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "admin".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('admin')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('admin')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('calendario/admi...')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php/calendario/admin
HTTP_REFERER=http://localhost/web/index.php/calendario/index?
---
2016/05/14 19:55:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "admin".' in C:\xampp\htdocs\web\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(270): CController->missingAction('admin')
#1 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('admin')
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('calendario/admi...')
#3 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/web/index.php/calendario/admin
HTTP_REFERER=http://localhost/web/index.php/calendario/index?
---
2016/05/14 21:45:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:45:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:45:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:45:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:46:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:46:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:46:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:46:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:46:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 21:46:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "web/assets/paraSHA1.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('web/assets/para...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/web/assets/paraSHA1.js
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/14 23:59:14 [error] [php] hash(): Unknown hashing algorithm: string to hash (C:\xampp\htdocs\web\protected\controllers\CalendarioController.php:14)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#2 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#4 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/calendario/registro
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (14)
in C:\xampp\htdocs\web\index.php (13)
2016/05/15 12:05:43 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\web\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente/update')
#10 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/web/cliente/update
---
2016/05/18 23:06:19 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.email" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\protected\components\UserIdentity.php(24): CComponent->__get('email')
#1 C:\xampp\htdocs\web\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/site/login
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/18 23:06:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\web\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente/update')
#10 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/web/cliente/update
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/18 23:08:50 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.email" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\protected\components\UserIdentity.php(24): CComponent->__get('email')
#1 C:\xampp\htdocs\web\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/site/login
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/18 23:09:31 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CUserIdentity.php(46): CComponent->__set('username', 'luis.proyectoap...')
#1 C:\xampp\htdocs\web\protected\models\LoginForm.php(51): CUserIdentity->__construct('luis.proyectoap...', 'luis')
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/site/login
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/18 23:10:13 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CUserIdentity.php(46): CComponent->__set('username', 'luis.proyectoap...')
#1 C:\xampp\htdocs\web\protected\models\LoginForm.php(51): CUserIdentity->__construct('luis.proyectoap...', 'luis')
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/site/login
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/18 23:16:03 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CUserIdentity.php(46): CComponent->__set('username', 'yiier')
#1 C:\xampp\htdocs\web\framework\gii\models\LoginForm.php(25): CUserIdentity->__construct('yiier', '1234')
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\framework\gii\controllers\DefaultController.php(43): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): DefaultController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/gii/default/login
HTTP_REFERER=http://localhost/web/gii/default/login
---
2016/05/18 23:16:24 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CUserIdentity.php(46): CComponent->__set('username', 'yiier')
#1 C:\xampp\htdocs\web\framework\gii\models\LoginForm.php(25): CUserIdentity->__construct('yiier', '1234')
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\framework\gii\controllers\DefaultController.php(43): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): DefaultController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/gii/default/login
HTTP_REFERER=http://localhost/web/gii/default/login
---
2016/05/18 23:16:38 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CUserIdentity.php(46): CComponent->__set('username', 'yiier')
#1 C:\xampp\htdocs\web\framework\gii\models\LoginForm.php(25): CUserIdentity->__construct('yiier', '1234')
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\framework\gii\controllers\DefaultController.php(43): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): DefaultController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/gii/default/login
HTTP_REFERER=http://localhost/web/gii/default/login
---
2016/05/18 23:16:41 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CUserIdentity.php(46): CComponent->__set('username', 'yiier')
#1 C:\xampp\htdocs\web\framework\gii\models\LoginForm.php(25): CUserIdentity->__construct('yiier', '1234')
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\framework\gii\controllers\DefaultController.php(43): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): DefaultController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/gii/default/login
HTTP_REFERER=http://localhost/web/gii/default/login
---
2016/05/18 23:16:47 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CUserIdentity.php(46): CComponent->__set('username', 'yiier')
#1 C:\xampp\htdocs\web\framework\gii\models\LoginForm.php(25): CUserIdentity->__construct('yiier', '1234')
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\framework\gii\controllers\DefaultController.php(43): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): DefaultController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/gii/default/login
HTTP_REFERER=http://localhost/web/gii/default/login
---
2016/05/18 23:18:15 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CUserIdentity.php(46): CComponent->__set('username', 'admin')
#1 C:\xampp\htdocs\web\protected\models\LoginForm.php(51): CUserIdentity->__construct('admin', 'admin')
#2 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\web\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/web/site/login
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/18 23:20:09 [error] [php] Undefined index: datos (C:\xampp\htdocs\web\protected\controllers\CalendarioController.php:14)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(286): CalendarioController->runAction()
#1 C:\xampp\htdocs\web\framework\web\CController.php(265): CalendarioController->runActionWithFilters()
#2 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CalendarioController->run()
#3 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/calendario/registro
in C:\xampp\htdocs\web\protected\controllers\CalendarioController.php (14)
in C:\xampp\htdocs\web\index.php (13)
2016/05/18 23:30:59 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'username='luis2' ANDpassword='luis' AND activo=1' at line 1. The SQL statement executed was: SELECT username, passwordFROM usernameWHERE username='luis2' ANDpassword='luis' AND activo=1.
in C:\xampp\htdocs\web\protected\components\UserIdentity.php (27)
in C:\xampp\htdocs\web\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\web\protected\controllers\SiteController.php (94)
2016/05/18 23:30:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'username='luis2' ANDpassword='luis' AND activo=1' at line 1. The SQL statement executed was: SELECT username, passwordFROM usernameWHERE username='luis2' ANDpassword='luis' AND activo=1' in C:\xampp\htdocs\web\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\web\framework\db\CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 C:\xampp\htdocs\web\protected\components\UserIdentity.php(27): CDbCommand->query()
#2 C:\xampp\htdocs\web\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\web\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\web\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/web/site/login
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/18 23:32:53 [error] [php] include(CDbConection.php): failed to open stream: No such file or directory (C:\xampp\htdocs\web\framework\YiiBase.php:432)
Stack trace:
#0 unknown(0): spl_autoload_call()
#1 C:\xampp\htdocs\web\framework\YiiBase.php(303): class_exists()
#2 C:\xampp\htdocs\web\framework\YiiBase.php(196): import()
#3 C:\xampp\htdocs\web\framework\base\CModule.php(393): createComponent()
#4 C:\xampp\htdocs\web\framework\base\CModule.php(103): CWebApplication->getComponent()
#5 C:\xampp\htdocs\web\protected\components\UserIdentity.php(20): CWebApplication->__get()
#6 C:\xampp\htdocs\web\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#7 C:\xampp\htdocs\web\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#8 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#9 C:\xampp\htdocs\web\framework\base\CModel.php(159): CInlineValidator->validate()
#10 C:\xampp\htdocs\web\protected\controllers\SiteController.php(94): LoginForm->validate()
#11 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#12 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\htdocs\web\framework\web\CController.php(286): SiteController->runAction()
#14 C:\xampp\htdocs\web\framework\web\CController.php(265): SiteController->runActionWithFilters()
#15 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): SiteController->run()
#16 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#17 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/site/login
in C:\xampp\htdocs\web\protected\components\UserIdentity.php (20)
in C:\xampp\htdocs\web\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\web\protected\controllers\SiteController.php (94)
2016/05/19 00:54:19 [error] [php] Use of undefined constant email - assumed 'email' (C:\xampp\htdocs\web\protected\components\UserIdentity.php:15)
Stack trace:
#0 C:\xampp\htdocs\web\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\web\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\web\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/site/login
in C:\xampp\htdocs\web\protected\components\UserIdentity.php (15)
in C:\xampp\htdocs\web\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\web\protected\controllers\SiteController.php (94)
2016/05/19 00:55:06 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap/admin')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/handicap/admin
HTTP_REFERER=http://localhost/web/handicap
---
2016/05/19 00:55:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('estado/admin')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/estado/admin
HTTP_REFERER=http://localhost/web/estado
---
2016/05/19 10:39:11 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente
HTTP_REFERER=http://localhost/web/cliente
---
2016/05/19 10:39:20 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente
HTTP_REFERER=http://localhost/web/estado
---
2016/05/19 10:39:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente
HTTP_REFERER=http://localhost/web/cita
---
2016/05/19 10:43:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cita')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cita
HTTP_REFERER=http://localhost/web/admin
---
2016/05/19 10:43:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente
HTTP_REFERER=http://localhost/web/cita
---
2016/05/19 10:43:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('estado')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/estado
HTTP_REFERER=http://localhost/web/cliente
---
2016/05/19 10:43:30 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('otro')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/otro
HTTP_REFERER=http://localhost/web/estado
---
2016/05/19 10:43:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/handicap
HTTP_REFERER=http://localhost/web/otro
---
2016/05/19 10:43:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('pieza')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/pieza
HTTP_REFERER=http://localhost/web/handicap
---
2016/05/19 10:43:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('mano')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/mano
HTTP_REFERER=http://localhost/web/pieza
---
2016/05/19 10:43:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('marcaPieza')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/marcaPieza
HTTP_REFERER=http://localhost/web/mano
---
2016/05/19 11:05:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente
HTTP_REFERER=http://localhost/web/admin
---
2016/05/19 11:05:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cita')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cita
HTTP_REFERER=http://localhost/web/cliente
---
2016/05/19 11:05:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('estado')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/estado
HTTP_REFERER=http://localhost/web/cita
---
2016/05/19 11:05:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('otro')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/otro
HTTP_REFERER=http://localhost/web/estado
---
2016/05/19 11:05:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/handicap
HTTP_REFERER=http://localhost/web/otro
---
2016/05/19 11:05:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('pieza')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/pieza
HTTP_REFERER=http://localhost/web/handicap
---
2016/05/19 11:05:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('mano')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/mano
HTTP_REFERER=http://localhost/web/pieza
---
2016/05/19 11:05:30 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('marcaPieza')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/marcaPieza
HTTP_REFERER=http://localhost/web/mano
---
2016/05/20 22:24:10 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente
HTTP_REFERER=http://localhost/web/admin
---
2016/05/20 22:24:13 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('otro')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/otro
HTTP_REFERER=http://localhost/web/admin
---
2016/05/20 22:24:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('pieza')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/pieza
HTTP_REFERER=http://localhost/web/admin
---
2016/05/20 22:49:19 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.isAdmin" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CWebUser.php(146): CComponent->__get('isAdmin')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CWebUser->__get('isAdmin')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site')
#20 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/web/site
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/20 22:49:21 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.isAdmin" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CWebUser.php(146): CComponent->__get('isAdmin')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CWebUser->__get('isAdmin')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\SiteController.php(98): CController->render('login', Array)
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('login')
#19 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#20 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/web/site/login
HTTP_REFERER=http://localhost/web/admin
---
2016/05/20 22:49:27 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.isAdmin" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CWebUser.php(146): CComponent->__get('isAdmin')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CWebUser->__get('isAdmin')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#20 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/web/admin
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/20 22:53:10 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.isAdminUser" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CWebUser.php(146): CComponent->__get('isAdminUser')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CWebUser->__get('isAdminUser')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#20 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/web/admin
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/20 23:19:44 [error] [php] Illegal offset type in isset or empty (C:\xampp\htdocs\web\framework\web\auth\CWebUser.php:812)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): SiteController->renderInternal()
#1 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#2 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#3 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#4 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): CContentDecorator->run()
#5 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): SiteController->endWidget()
#6 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): SiteController->endContent()
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): SiteController->renderInternal()
#9 C:\xampp\htdocs\web\framework\web\CController.php(784): SiteController->renderFile()
#10 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): SiteController->render()
#11 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#12 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\htdocs\web\framework\web\CController.php(286): SiteController->runAction()
#14 C:\xampp\htdocs\web\framework\web\CController.php(265): SiteController->runActionWithFilters()
#15 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): SiteController->run()
#16 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#17 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/admin
in C:\xampp\htdocs\web\protected\views\layouts\main.php (36)
in C:\xampp\htdocs\web\protected\views\layouts\column1.php (6)
in C:\xampp\htdocs\web\protected\controllers\SiteController.php (32)
2016/05/20 23:21:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente
HTTP_REFERER=http://localhost/web/admin
---
2016/05/20 23:26:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "cilente/index".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cilente/index')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/cilente/index
---
2016/05/20 23:26:41 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente/
---
2016/05/20 23:27:00 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('cliente')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/cliente/
---
2016/05/21 10:57:37 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.cliente" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\base\CModule.php(105): CComponent->__get('cliente')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CModule->__get('cliente')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site')
#20 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/web/site
HTTP_REFERER=http://localhost/web/otro
---
2016/05/21 10:57:46 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.cliente" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\base\CModule.php(105): CComponent->__get('cliente')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CModule->__get('cliente')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site')
#20 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/web/site
HTTP_REFERER=http://localhost/web/otro
---
2016/05/21 11:01:02 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.cliente" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\base\CModule.php(105): CComponent->__get('cliente')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CModule->__get('cliente')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div class="spa...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div class="spa...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column2.php(22): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\OtroController.php(130): CController->render('index', Array)
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): OtroController->actionIndex()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(40): CFilterChain->run()
#18 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#19 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#20 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#22 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#24 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('otro')
#25 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#26 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#27 {main}
REQUEST_URI=/web/otro
HTTP_REFERER=http://localhost/web/admin
---
2016/05/21 11:01:05 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.cliente" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\base\CModule.php(105): CComponent->__get('cliente')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CModule->__get('cliente')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#20 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/web/admin
HTTP_REFERER=http://localhost/web/
---
2016/05/21 11:01:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contact".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('contact')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/contact
---
2016/05/21 11:01:16 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.cliente" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\base\CModule.php(105): CComponent->__get('cliente')
#1 C:\xampp\htdocs\web\protected\views\layouts\main.php(36): CModule->__get('cliente')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\web\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\web\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\web\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\web\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\web\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\web\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#14 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#15 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('contact')
#19 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#20 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/web/site/contact
---
2016/05/21 11:02:08 [error] [php] Object of class CWebUser could not be converted to string (C:\xampp\htdocs\web\protected\views\site\contact.php:87)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\SiteController.php(72): SiteController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/site/contact
in C:\xampp\htdocs\web\protected\views\site\contact.php (87)
in C:\xampp\htdocs\web\protected\controllers\SiteController.php (72)
in C:\xampp\htdocs\web\index.php (13)
2016/05/21 11:04:12 [error] [exception.CException] exception 'CException' with message 'CWebUser and its behaviors do not have a method or closure named "getNumber".' in C:\xampp\htdocs\web\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\web\protected\views\site\contact.php(87): CComponent->__call('getNumber', Array)
#1 C:\xampp\htdocs\web\protected\views\site\contact.php(87): CWebUser->getNumber()
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\web\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\web\framework\web\CController.php(782): CController->renderPartial('contact', Array, true)
#6 C:\xampp\htdocs\web\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#7 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#8 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('contact')
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#13 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/web/site/contact
---
2016/05/21 11:07:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "handicaps".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicaps')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/handicaps
---
2016/05/21 11:07:42 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/handicap
---
2016/05/21 11:09:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "handicaps".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicaps')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/handicaps
---
2016/05/21 11:09:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "handicaps".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicaps')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/handicaps
---
2016/05/21 11:09:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/handicap
---
2016/05/21 11:09:51 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/handicap
---
2016/05/21 11:25:24 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\web\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\web\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\web\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\web\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\web\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('handicap')
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/web/handicap
HTTP_REFERER=http://localhost/web/site/login
---
2016/05/21 13:27:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:28:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:28:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:28:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:28:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:29:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:29:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:29:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:29:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:30:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:31:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:31:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:33:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:33:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:33:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:33:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:33:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:33:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:34:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:34:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:34:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:35:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:36:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:36:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:38:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "assets/registro.js".' in C:\xampp\htdocs\web\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('assets/registro...')
#1 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/web/assets/registro.js
HTTP_REFERER=http://localhost/web/registro
---
2016/05/21 13:45:04 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\registro\index.php:31)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): RegistroController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): RegistroController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\RegistroController.php(10): RegistroController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): RegistroController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): RegistroController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): RegistroController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): RegistroController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/registro
in C:\xampp\htdocs\web\protected\views\registro\index.php (31)
in C:\xampp\htdocs\web\protected\controllers\RegistroController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/21 13:45:21 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\registro\index.php:24)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): RegistroController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): RegistroController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\RegistroController.php(10): RegistroController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): RegistroController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): RegistroController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): RegistroController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): RegistroController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/registro
in C:\xampp\htdocs\web\protected\views\registro\index.php (24)
in C:\xampp\htdocs\web\protected\controllers\RegistroController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/21 13:46:54 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.pageTittle" is not defined.' in C:\xampp\htdocs\web\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\web\framework\base\CModule.php(105): CComponent->__get('pageTittle')
#1 C:\xampp\htdocs\web\protected\views\calendario\index.php(9): CModule->__get('pageTittle')
#2 C:\xampp\htdocs\web\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\web\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, true)
#4 C:\xampp\htdocs\web\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, true)
#5 C:\xampp\htdocs\web\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\web\protected\controllers\CalendarioController.php(10): CController->render('index')
#7 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): CalendarioController->actionIndex()
#8 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\web\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\web\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController('calendario')
#13 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\web\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/web/calendario
HTTP_REFERER=http://localhost/web/calendario
---
2016/05/21 13:48:14 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\registro\index.php:18)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): RegistroController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): RegistroController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\RegistroController.php(10): RegistroController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): RegistroController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): RegistroController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): RegistroController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): RegistroController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/registro
in C:\xampp\htdocs\web\protected\views\registro\index.php (18)
in C:\xampp\htdocs\web\protected\controllers\RegistroController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/21 13:48:46 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\registro\index.php:18)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): RegistroController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): RegistroController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\RegistroController.php(10): RegistroController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): RegistroController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): RegistroController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): RegistroController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): RegistroController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/registro
in C:\xampp\htdocs\web\protected\views\registro\index.php (18)
in C:\xampp\htdocs\web\protected\controllers\RegistroController.php (10)
in C:\xampp\htdocs\web\index.php (13)
2016/05/21 13:49:32 [error] [php] Undefined variable: model (C:\xampp\htdocs\web\protected\views\registro\index.php:30)
Stack trace:
#0 C:\xampp\htdocs\web\framework\web\CController.php(869): RegistroController->renderFile()
#1 C:\xampp\htdocs\web\framework\web\CController.php(782): RegistroController->renderPartial()
#2 C:\xampp\htdocs\web\protected\controllers\RegistroController.php(10): RegistroController->render()
#3 C:\xampp\htdocs\web\framework\web\actions\CInlineAction.php(49): RegistroController->actionIndex()
#4 C:\xampp\htdocs\web\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\web\framework\web\CController.php(286): RegistroController->runAction()
#6 C:\xampp\htdocs\web\framework\web\CController.php(265): RegistroController->runActionWithFilters()
#7 C:\xampp\htdocs\web\framework\web\CWebApplication.php(282): RegistroController->run()
#8 C:\xampp\htdocs\web\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\web\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\web\index.php(13): CWebApplication->run()
REQUEST_URI=/web/registro
in C:\xampp\htdocs\web\protected\views\registro\index.php (30)
in C:\xampp\htdocs\web\protected\controllers\RegistroController.php (10)
in C:\xampp\htdocs\web\index.php (13)
